DROP DATABASE IF EXISTS SCM_CLINICA;
CREATE DATABASE IF NOT EXISTS SCM_CLINICA;
USE SCM_CLINICA;

CREATE TABLE T_SCM_PACIENTE (
    ID_PACIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NM_PACIENTE VARCHAR(100) NOT NULL,
    CPF_PACIENTE VARCHAR(14) UNIQUE NOT NULL,
    TEL_PACIENTE VARCHAR(20),
    END_PACIENTE VARCHAR(150),
    HIST_PACIENTE TEXT
);


CREATE TABLE T_SCM_MEDICO (
    ID_MEDICO INT AUTO_INCREMENT PRIMARY KEY,
    NM_MEDICO VARCHAR(100) NOT NULL,
    CRM_MEDICO VARCHAR(20) UNIQUE NOT NULL,
    ESP_MEDICO VARCHAR(100),
    HOR_DISPONIVEIS TEXT,
    LOGIN_MEDICO VARCHAR(50) UNIQUE NOT NULL,
    SENHA_MEDICO VARCHAR(255) NOT NULL
);


CREATE TABLE T_SCM_AGENDAMENTO (
    ID_AGENDAMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_PACIENTE INT NOT NULL,
    ID_MEDICO INT NOT NULL,
    DT_CONSULTA DATE NOT NULL,
    HR_CONSULTA TIME NOT NULL,
    ST_CONSULTA ENUM('AGENDADO', 'REALIZADO', 'CANCELADO') DEFAULT 'AGENDADO',
    FOREIGN KEY (ID_PACIENTE) REFERENCES T_SCM_PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES T_SCM_MEDICO(ID_MEDICO),
    CONSTRAINT UQ_CONSULTA_UNICA UNIQUE (ID_MEDICO, DT_CONSULTA, HR_CONSULTA)
);


CREATE TABLE T_SCM_ATENDIMENTO (
    ID_ATENDIMENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_AGENDAMENTO INT NOT NULL,
    SINTOMAS TEXT,
    DIAGNOSTICO TEXT,
    OBSERVACOES TEXT,
    DT_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_AGENDAMENTO) REFERENCES T_SCM_AGENDAMENTO(ID_AGENDAMENTO)
);
 